export default {
  // Common words and phrases used across the app
  common: {
    // General
    all: 'All',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    delete: 'Delete',
    retry: 'Retry',
    loading: 'Loading...',
    unknown: 'Unknown',
    notAvailable: 'Not Available',
    // Roles
    admin: 'Admin',
    waiter: 'Waiter',
    cashier: 'Cashier',
    // Payment
    cash: 'Cash',
    card: 'Card',
    uzs: 'UZS',
    // Statuses
    status: 'Status',
    status_new: 'New',
    status_preparing: 'Preparing',
    status_served: 'Served',
    status_paid: 'Paid',
    // Table Statuses
    table_available: 'Available',
    table_occupied: 'Occupied',
    table_reserved: 'Reserved',
  },

  // Text specific to screens
  screens: {
    // Auth
    login_welcome: 'Welcome!',
    login_subtitle: 'Please enter your credentials to log in.',
    login_email_placeholder: 'Email',
    login_password_placeholder: 'Password',
    login_button: 'Login',

    // Admin -> Menu Management
    menu_management_title: 'Menu Management',
    menu_list_no_items: 'No menu items found.',
    menu_list_add_prompt: "Tap the '+' button to add one!",
    add_item_title: 'Add New Menu Item',
    edit_item_title: 'Edit Item',
    item_form_name_placeholder: 'Item Name (e.g., Pilaf)',
    item_form_desc_placeholder: 'Description',
    item_form_price_placeholder: 'Price (e.g., 30000)',
    item_form_category_placeholder: 'Category (e.g., Hot Dishes)',
    item_form_select_image: 'Select an Image',
    item_form_change_image: 'Change Image',
    item_form_add_button: 'Add Item',
    item_form_update_button: 'Update Item',

    // Admin -> User Management
    user_management_title: 'User Management',
    user_list_no_users: 'No users found.',
    add_user_title: 'Add New User',
    user_form_name_placeholder: 'Full Name (e.g., John Doe)',
    user_form_password_placeholder: 'Password (min. 6 characters)',
    user_form_assign_role: 'Assign Role',
    user_form_create_button: 'Create User',
    user_roles_title: 'Manage User Roles',
    user_roles_no_staff: 'No staff members found.',
    
    // Admin -> Reports
    reports_title: 'Reports',
    reports_sales_title: 'Sales Report',
    reports_sales_desc: 'Analyze revenue, transactions, and sales trends.',
    reports_staff_title: 'Staff Performance',
    reports_staff_desc: 'Track orders and sales generated by each waiter.',
    reports_table_title: 'Table Performance',
    reports_table_desc: 'View occupancy and revenue statistics for each table.',
    report_from: 'From:',
    report_to: 'To:',
    report_total_revenue: 'Total Revenue',
    report_total_transactions: 'Total Transactions',
    report_avg_transaction: 'Avg. Transaction',
    report_sales_trend: 'Sales Trend',
    report_no_sales_data: 'No sales data for the selected period.',
    report_transactions: 'Transactions',
    report_order_id: 'Order ID:',
    report_no_staff_data: 'No performance data found for this period.',
    report_total_orders: 'Total Orders:',
    report_total_sales: 'Total Sales:',
    report_table_num: 'Table #',
    report_num_orders: 'Number of Orders',
    report_no_table_data: 'No data found for this period.',

    // Admin -> Settings
    settings_title: 'Settings',
    settings_account: 'Account',
    settings_restaurant_profile: 'Restaurant Profile',
    settings_general: 'General',
    settings_appearance: 'Appearance',
    settings_language: 'Language',
    settings_about: 'About',
    settings_app_version: 'App Version',
    settings_logout: 'Log Out',
    
    // Waiter
    waiter_tables_title: 'Table Status',
    waiter_menu_title: 'Table #{tableNumber} - Menu',
    waiter_cart_title: 'Current Order',
    waiter_cart_empty: 'Cart is empty',
    waiter_place_order_button: 'Place Order',
    waiter_history_title: 'My Orders (Today)',
    waiter_history_empty: 'You have no orders for today.',
    waiter_order_details_title: 'Order Details',
    waiter_order_items: 'Items',
    waiter_order_time: 'Time:',
    waiter_order_total: 'Total Amount:',

    // Cashier
    cashier_daily_transactions_title: "Today's Transactions",
    cashier_total_revenue: 'Total Revenue',
    cashier_no_payments_today: 'No payments for today.',
    cashier_orders_for_payment_title: 'Orders for Payment',
    cashier_no_orders_for_payment: 'No orders for payment right now.',
    cashier_confirm_payment_title: 'Confirm Payment',
    cashier_order_contents: 'Order Contents',
    cashier_payment_method: 'Payment Method',
    cashier_confirm_payment_button: 'Confirm Payment',
  },

  // Alert messages
  alerts: {
    // General
    error_title: 'An Error Occurred',
    error_unknown: 'An unknown error occurred.',
    // Login
    login_failed_title: 'Login Failed',
    login_validation_error_title: 'Validation Error',
    login_validation_error_message: 'Please enter both email and password.',
    error_invalid_credentials: 'Invalid email or password.',
    error_invalid_email_format: 'Email address is badly formatted.',
    error_login_generic: 'An error occurred during login.',
    error_logout_generic: 'An error occurred during logout.',
    error_user_data_not_found: 'User data not found in the database.',
    // Menu
    menu_incomplete_form_title: 'Incomplete Form',
    menu_incomplete_form_message: 'Please fill all fields and select an image.',
    menu_upload_error_title: 'Upload Error',
    menu_upload_error_message: 'Failed to upload image. Please try again.',
    menu_add_error: 'An error occurred while adding the item.',
    menu_add_success: 'Menu item added successfully!',
    menu_fetch_error: 'Could not fetch item data.',
    menu_update_success: 'Menu item updated successfully!',
    menu_delete_title: 'Delete Item',
    menu_delete_confirm: 'Are you sure you want to delete "{itemName}"? This action cannot be undone.',
    menu_delete_success: '"{itemName}" has been deleted.',
    menu_delete_error: 'Failed to delete item. Please try again.',
    // User
    user_add_incomplete_form: 'Please fill all fields.',
    user_add_invalid_email: 'Please enter a valid email address.',
    user_add_weak_password: 'Password must be at least 6 characters long.',
    user_add_success: 'User "{userName}" created successfully as a {role}.',
    user_add_failed_title: 'Creation Failed',
    user_add_email_in_use: 'This email address is already in use by another account.',
    user_delete_confirm_title: 'Confirm Deletion',
    user_delete_confirm_message: 'Are you sure you want to delete the user "{userName}"?',
    user_delete_record_deleted_title: 'Record Deleted',
    user_delete_record_deleted_message: 'The Firestore record for {email} has been deleted.\n\nIMPORTANT: To fully remove login access, you must now manually delete this user from the "Authentication" section of your Firebase Console.',
    // Order
    order_empty_title: 'Empty Order',
    order_empty_message: 'Please select at least one item to place an order.',
    order_placed_success: 'The order has been sent to the kitchen.',
    // Payment
    payment_missing_order: 'Order details are missing.',
    payment_success: 'Payment completed successfully!',
    payment_error: 'An error occurred during payment. Please try again.',
    // Settings
    feature_not_implemented_title: 'Feature Not Implemented',
    feature_not_implemented_message: 'Navigation to "{screenName}" is not yet set up.',
    logout_confirm_title: 'Log Out',
    logout_confirm_message: 'Are you sure you want to log out?',
  }
};