import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { createStackNavigator } from '@react-navigation/stack';
import { MaterialIcons } from '@expo/vector-icons';

// Import the specific report screens
import SalesReportScreen from './Reports/SalesReport';
import StaffPerformanceScreen from './Reports/StaffPerformance';
import TablePerformanceScreen from './Reports/TablePerformance';

const Stack = createStackNavigator();

// Reports Hub Screen
const ReportsHubScreen = ({ navigation }) => {
  const menuItems = [
    {
      title: 'Sales Report',
      description: 'Analyze revenue, transactions, and sales trends.',
      icon: 'monetization-on',
      color: '#28a745',
      screen: 'SalesReport',
    },
    {
      title: 'Staff Performance',
      description: 'Track orders and sales generated by each waiter.',
      icon: 'people',
      color: '#007bff',
      screen: 'StaffPerformance',
    },
    {
      title: 'Table Performance',
      description: 'View occupancy and revenue statistics for each table.',
      icon: 'restaurant',
      color: '#ffc107',
      screen: 'TablePerformance',
    },
  ];

  return (
    <ScrollView style={styles.hubContainer}>
      {menuItems.map((item, index) => (
        <TouchableOpacity
          key={index}
          activeOpacity={0.85}
          style={styles.menuItem}
          onPress={() => navigation.navigate(item.screen)}
        >
          <View style={[styles.iconContainer, { backgroundColor: item.color }]}>
            <MaterialIcons name={item.icon} size={32} color="#fff" />
          </View>
          <View style={styles.textContainer}>
            <Text style={styles.menuItemTitle}>{item.title}</Text>
            <Text style={styles.menuItemDescription}>{item.description}</Text>
          </View>
          <MaterialIcons name="chevron-right" size={28} color="#adb5bd" />
        </TouchableOpacity>
      ))}
    </ScrollView>
  );
};

// Reports Stack
const ReportsStack = () => {
  return (
    <Stack.Navigator
      initialRouteName="ReportsHub"
      screenOptions={{
        headerStyle: {
          backgroundColor: '#343a40',
        },
        headerTintColor: '#fff',
        headerTitleStyle: {
          fontWeight: 'bold',
        },
        headerBackTitleVisible: false,
      }}
    >
      <Stack.Screen
        name="ReportsHub"
        component={ReportsHubScreen}
        options={{ title: 'Reports' }}
      />
      <Stack.Screen
        name="SalesReport"
        component={SalesReportScreen}
        options={{ title: 'Sales Report' }}
      />
      <Stack.Screen
        name="StaffPerformance"
        component={StaffPerformanceScreen}
        options={{ title: 'Staff Performance' }}
      />
      <Stack.Screen
        name="TablePerformance"
        component={TablePerformanceScreen}
        options={{ title: 'Table Performance' }}
      />
    </Stack.Navigator>
  );
};

const styles = StyleSheet.create({
  hubContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    paddingTop: 10,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    marginHorizontal: 10,
    marginBottom: 12,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  iconContainer: {
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
  },
  textContainer: {
    flex: 1,
    marginLeft: 15,
  },
  menuItemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#212529',
  },
  menuItemDescription: {
    fontSize: 14,
    color: '#6c757d',
    marginTop: 2,
  },
});

export default ReportsStack;
